<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<PackageId>InfluxData.Net.Latest</PackageId>
		<Version>2.0.1</Version>
		<NuspecProperties>version=$(Version)</NuspecProperties>
		<AssemblyVersion>2.0.0.1</AssemblyVersion>
		<FileVersion>2.0.0.1</FileVersion>
		<Author>Sadaqat Hussain</Author>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\InfluxData.Net.Common\InfluxData.Net.Common.csproj" />
		<ProjectReference Include="..\InfluxData.Net.InfluxDb\InfluxData.Net.InfluxDb.csproj" />
		<ProjectReference Include="..\InfluxData.Net.Kapacitor\InfluxData.Net.Kapacitor.csproj" />
	</ItemGroup>

</Project>
