<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <PackageId>InfluxData.Net_Latest</PackageId>
    <Version>1.0.1</Version>
    <Authors>InfluxData.Net Contributors</Authors>
    <Description>InfluxData.Net is a portable .NET library for InfluxDB and Kapacitor.</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfluxData.Net.Common\InfluxData.Net.Common.csproj" />
    <ProjectReference Include="..\InfluxData.Net.InfluxDb\InfluxData.Net.InfluxDb.csproj" />
    <ProjectReference Include="..\InfluxData.Net.Kapacitor\InfluxData.Net.Kapacitor.csproj" />
  </ItemGroup>

</Project>
